name: Job Automation

on:
  workflow_dispatch:

  schedule:
    - cron: "30 3 * * *"

jobs:

  job-search:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run job automation
        env:
          JOOBLE_API_KEY: "bafcd2f6-18ed-4f21-b1d2-cb06b34e56af"
        run: |
          python jobs.py
