name: Job Automation

on:
  workflow_dispatch:

  schedule:
    - cron: "30 3 * * *"

jobs:

  job-search:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run job automation
        env:
          JOOBLE_API_KEY: ${{ secrets.JOOBLE_API_KEY }}
        run: |
          python jobs.py
